# Generated by Django 4.0.3 on 2022-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='assets/icons/avatar.svg', null=True, upload_to=''),
        ),
    ]
